### ISSUE TITLE
Vue files?

### ISSUE THREAD

**Issue by stefanpkc** [Bixie/intellij-uikit#4]
Since uikit is used a lot in pagekit which uses vuejs a lot, it should also work in that context I think.

**Comment by malles** [comment]
I set up phpstorm to treat .vue file as .html files, and html and js syntax work fine that way.
Vue is not even an option for a context here.
![image](https://cloud.githubusercontent.com/assets/5442402/11346411/d2ded880-921c-11e5-818e-c2b140a84b62.png)
